actions:
  blame:
    command: tig blame $filename +$line_number
    position: floating
  database:
    command: lazysql
    position: floating
  explorer:
    position: left
    percent: 20
    command: YAZI_CONFIG_HOME=~/.config/yazi/filetree yazi
    # command: br
  fzf:
    command: |
      helix-fzf.sh \$(rg --line-number --column --no-heading --smart-case . | fzf --delimiter : --preview 'bat --style=full --color=always --highlight-line {2} {1}' --preview-window '~3,+{2}+3/2' | awk '{ print \$1 }' | cut -d: -f1,2,3)
  generate_tests:
    command: gotests -w -all $filename
  lazygit:
    command: lazygit
    position: floating
  lint:
    extensions:
      go: golangci-lint run -v $filename
  mock:
    command: mockery --with-expecter --dir $basedir --name $interface_name
  open:
    command: helix-browse.sh $filename $line_number
  present:
    position: right
    extensions:
      md: presenterm --theme terminal-dark $filename
  run:
    # position: floating
    extensions:
      go: go run $basedir/*.go
      md: glow -p $filename
      rs: cargo run
  slumber:
    position: floating
    command: slumber -f ../slumber.yml
  sql_local:
    position: right
    percent: 30
    command: mycli --auto-vertical-output $MYSQL_LOCAL_DSN
  sql_test:
    position: right
    percent: 30
    command: mycli --auto-vertical-output $MYSQL_TEST_DSN
  test:
    extensions:
      go: go test -run=$test_name -v ./$basedir/...
      hurl: hurl --test --very-verbose --color $filename
      rs: cargo test
